test_configs = [
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 3,
    #     'neurones': 100,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 10,
    #     'batch_size': 16
    # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 3,
    #     'neurones': 100,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 30,
    #     'batch_size': 16
    # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 3,
    #     'neurones': 100,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 50,
    #     'batch_size': 16
    # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 3,
    #     'neurones': 100,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 10,
    #     'batch_size': 32
    # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 3,
    #     'neurones': 100,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 30,
    #     'batch_size': 32
    # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 3,
    #     'neurones': 100,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 50,
    #     'batch_size': 32
    # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 3,
    #     'neurones': 100,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 10,
    #     'batch_size': 64
    # },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 3,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 30,
    #             'batch_size': 64
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 3,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 50,
    #             'batch_size': 64
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 3,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 10,
    #             'batch_size': 128
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 3,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 30,
    #             'batch_size': 128
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 3,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 50,
    #             'batch_size': 128
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 5,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 10,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 5,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 30,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 5,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 50,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 10,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 10,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 10,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 30,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 10,
    #             'neurones': 100,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 50,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 3,
    #             'neurones': 200,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 10,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 3,
    #             'neurones': 200,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 30,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 3,
    #             'neurones': 200,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 50,
    #             'batch_size': 32
    #         },
    #         {
    #             'symbol': 'BTCUSDT',
    #             'timeframe': '30m',
    #             'layers': 5,
    #             'neurones': 200,
    #             'columns': ['open', 'high', 'low', 'close',
    #                         'aroon_25_up', 'aroon_25_down',
    #                         'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                         'fractal_5_bullish', 'fractal_5_bearish'],
    #             'sequence_length': 30,
    #             'split_index': 0.7,
    #             'epochs': 10,
    #             'batch_size': 32
    #         },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 5,
    #     'neurones': 200,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 30,
    #     'batch_size': 32
    # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 10,
    #     'neurones': 200,
    #     'columns': ['open', 'high', 'low', 'close',
    #                 'aroon_25_up', 'aroon_25_down',
    #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    #                 'fractal_5_bullish', 'fractal_5_bearish'],
    #     'sequence_length': 30,
    #     'split_index': 0.7,
    #     'epochs': 50,
    #     'batch_size': 32
    # },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '30m',
        'layers': 5,
        'neurones': 500,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 30,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '30m',
        'layers': 10,
        'neurones': 500,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '30m',
        'layers': 5,
        'neurones': 500,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 30,
        'batch_size': 64
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '30m',
        'layers': 10,
        'neurones': 500,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 64
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '30m',
        'layers': 5,
        'neurones': 500,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 30,
        'batch_size': 128
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '30m',
        'layers': 10,
        'neurones': 500,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 128
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '15m',
        'layers': 5,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 30,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '15m',
        'layers': 10,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '5m',
        'layers': 5,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 30,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '5m',
        'layers': 10,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '1h',
        'layers': 5,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 30,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '1h',
        'layers': 10,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '2h',
        'layers': 5,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '2h',
        'layers': 10,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '4h',
        'layers': 5,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 30,
        'batch_size': 32
    },
    {
        'symbol': 'BTCUSDT',
        'timeframe': '4h',
        'layers': 10,
        'neurones': 200,
        'columns': ['open', 'high', 'low', 'close',
                    'aroon_25_up', 'aroon_25_down',
                    'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
                    'fractal_5_bullish', 'fractal_5_bearish'],
        'sequence_length': 30,
        'split_index': 0.7,
        'epochs': 50,
        'batch_size': 32
    },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 5,
    # #     'neurones': 1000,
    # #     'columns': ['open', 'high', 'low', 'close'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 1,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 10,
    # #     'neurones': 1000,
    # #     'columns': ['open', 'high', 'low', 'close'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 1,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 20,
    # #     'neurones': 1000,
    # #     'columns': ['open', 'high', 'low', 'close'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 1,
    # # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 50,
    #     'neurones': 1000,
    #     'columns': ['open', 'high', 'low', 'close'],
    #     'sequence_length': 30,
    #     'split_index': 0.8,
    #     'epochs': 1,
    # },
    # {
    #     'symbol': 'BTCUSDT',
    #     'timeframe': '30m',
    #     'layers': 20,
    #     'neurones': 1000,
    #     'columns': ['open', 'high', 'low', 'close'],
    #     'sequence_length': 30,
    #     'split_index': 0.8,
    #     'epochs': 1,
    # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 5,
    # #     'neurones': 50,
    # #     'columns': ['open', 'high', 'low', 'close'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 2,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 5,
    # #     'neurones': 50,
    # #     'columns': ['open', 'high', 'low', 'close'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 3,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 5,
    # #     'neurones': 50,
    # #     'columns': ['open', 'high', 'low', 'close'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 5,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 5,
    # #     'neurones': 50,
    # #     'columns': ['open', 'high', 'low', 'close'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 10,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 5,
    # #     'neurones': 50,
    # #     'columns': ['open', 'high', 'low', 'close'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 2,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 5,
    # #     'neurones': 50,
    # #     'columns': ['open', 'high', 'low', 'close',
    # #                 'aroon_25_up', 'aroon_25_down',
    # #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    # #                 'fractal_5_bullish', 'fractal_5_bearish'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 1,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 10,
    # #     'neurones': 50,
    # #     'columns': ['open', 'high', 'low', 'close',
    # #                 'aroon_25_up', 'aroon_25_down',
    # #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    # #                 'fractal_5_bullish', 'fractal_5_bearish'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 1,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 10,
    # #     'neurones': 100,
    # #     'columns': ['open', 'high', 'low', 'close',
    # #                 'aroon_25_up', 'aroon_25_down',
    # #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    # #                 'fractal_5_bullish', 'fractal_5_bearish'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 1,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 10,
    # #     'neurones': 100,
    # #     'columns': ['open', 'high', 'low', 'close',
    # #                 'aroon_25_up', 'aroon_25_down',
    # #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    # #                 'fractal_5_bullish', 'fractal_5_bearish'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 2,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 10,
    # #     'neurones': 100,
    # #     'columns': ['open', 'high', 'low', 'close',
    # #                 'aroon_25_up', 'aroon_25_down',
    # #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    # #                 'fractal_5_bullish', 'fractal_5_bearish'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 3,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 10,
    # #     'neurones': 100,
    # #     'columns': ['open', 'high', 'low', 'close',
    # #                 'aroon_25_up', 'aroon_25_down',
    # #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    # #                 'fractal_5_bullish', 'fractal_5_bearish'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 5,
    # # },
    # # {
    # #     'symbol': 'BTCUSDT',
    # #     'timeframe': '30m',
    # #     'layers': 10,
    # #     'neurones': 500,
    # #     'columns': ['open', 'high', 'low', 'close',
    # #                 'aroon_25_up', 'aroon_25_down',
    # #                 'ma_7', 'ma_26', 'ma_golden_cross_7_26', 'ma_death_cross_7_26',
    # #                 'fractal_5_bullish', 'fractal_5_bearish'],
    # #     'sequence_length': 30,
    # #     'split_index': 0.8,
    # #     'epochs': 5,
    # # },
]